name: Hola Mundo

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        run: echo "Hello World!"

      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: En que carpeta estoy
        run: pwd

      - name: Listado de archivos
        run: ls -la

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verificar node
        run: node --version

      - name: Verificar npm
        run: npm --version

      - name: Install ci
        working-directory: ./Clase 17/tres-en-raya
        run: npm ci

      - name: Guardar resultado
        working-directory: ./Clase 17/tres-en-raya
        run: npm run build

      - name: Configurar Github Pages
        uses: actions/configure-pages@v5

      - name: Subir resultado
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Clase 17/tres-en-raya/dist

      - name: Publicar aplicación
        uses: actions/deploy-pages@v4