name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias del frontend
        working-directory: ./Proyecto Final/frontend
        run: npm ci

      - name: Ejecutar lint del frontend
        working-directory: ./Proyecto Final/frontend
        run: npm run lint

      - name: Instalar dependencias del backend
        working-directory: ./Proyecto Final/backend
        run: npm ci

      - name: Ejecutar lint del backend
        working-directory: ./Proyecto Final/backend
        run: npm run lint